version: '3.7'
services:
  postgres:
    container_name: gms-postgres-container
    image: postgres:11
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root

  mongo:
    container_name: gms-mongo-container
    image: mongo:latest
    volumes:
      - ./docker/mongo/data:/data/db
    ports:
      - 27017:27017

  redis:
    container_name: gms-redis
    image: redis:latest
    ports:
      - "6379:6379"

  backend: &backend
    container_name: gms-backend-container
    build:
      context: ./
      dockerfile: ./docker/backend/dev/Dockerfile
    command: "./entrypoint.sh"
    environment:
      - DJANGO_PROJECT_SECRET=your_secret_here
      - DJANGO_PROJECT_DEBUG=True
      - DJANGO_ALLOWED_HOST=127.0.0.1
      - DJANGO_CORS_ORIGIN_WHITELIST=http://localhost:8080
      - DJANGO_AUTH0_API_IDENTIFIER=https://django-vuejs-api
      - DJANGO_AUTH0_DOMAIN=dev-z912l6w0.eu.auth0.com
    volumes:
      - ./backend:/code/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
      - celery_worker

  celery_worker:
    container_name: gms-celery
    <<: *backend
    command: "celery worker -A backend.settings"
    ports: []
    depends_on:
      - redis
      - postgres
      - mongo

  frontend:
    container_name: gms-frontend-container
    build:
      context: ./
      dockerfile: ./docker/frontend/dev/Dockerfile
    volumes:
      - ./frontend:/app
    command: "npm run dev"
    environment:
      - HOST=0.0.0.0
      - VUE_AUTH0_CLIENT_ID='tnlMjimbEuNye055qr2C3Wd783M9z47A'
      - VUE_AUTH0_DOMAIN='dev-z912l6w0.eu.auth0.com'
      - VUE_AUTH0_CALLBACK_REDIRECT='http://localhost:8080/callback'
      - VUE_AUTH0_API_IDENTIFIER='https://django-vuejs-api'
      - VUE_API_BASE_URL='http://127.0.0.1:8000'
    ports:
      - "8080:8080"
