version: '3.7'
services:
  backend:
    image: registry.gitlab.com/vtr0n/playmusicstats:DJANGO_latest
    command: "sh -c './manage.py runserver 0.0.0.0:8000'"
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo

  frontend:
    image: registry.gitlab.com/vtr0n/playmusicstats:VUE_latest
    command: "nginx -g 'daemon off;'"
    environment:
      - HOST=0.0.0.0
      - REDIRECT_URL=http://localhost:80/callback
    ports:
      - "80:80"
