version: '3.7'
services:
  postgres:
    container_name: gms-postgres-container
    image: postgres:11
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    restart: always
    ports:
      - 10000:5432
    environment:
      POSTGRES_PASSWORD: root

  mongo:
    container_name: gms-mongo-container
    image: mongo:latest
    volumes:
      - ./docker/mongo/data:/data/db
    restart: always
    ports:
      - 10001:27017

  redis:
    container_name: gms-redis
    image: redis:latest
    restart: always
    ports:
      - "10002:6379"

  backend: &backend
    image: registry.gitlab.com/vtr0n/playmusicstats:DJANGO_latest
    command: "./entrypoint.sh"
    env_file: .env
    restart: always
    ports:
      - "10003:8000"
    depends_on:
      - postgres
      - mongo

  celery_worker:
    container_name: gms-celery
    <<: *backend
    command: "celery worker -A backend.settings -l ERROR"
    ports: []
    depends_on:
      - redis
      - postgres
      - mongo

  frontend:
    image: registry.gitlab.com/vtr0n/playmusicstats:VUE_latest
    command: "nginx -g 'daemon off;'"
    env_file: .env
    restart: always
    ports:
      - "10004:80"