version: '3.7'
services:
  postgres:
    container_name: gms-postgres-container
    image: postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root

  mongo:
    container_name: gms-mongo-container
    image: mongo:latest
    volumes:
      - ./docker/mongo/data:/data/db
    ports:
      - 27017:27017

  backend:
    container_name: gms-backend-container
    build:
      context: ./
      dockerfile: ./docker/backend/dev/Dockerfile
    command: "./entrypoint.sh"
    # command: "./manage.py update_users_stats"
    environment:
      - DJANGO_PROJECT_SECRET=your_secret_here
      - DJANGO_PROJECT_DEBUG=False
      - DJANGO_ALLOWED_HOST=127.0.0.1
    volumes:
      - ./backend:/code/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo

  frontend:
    container_name: gms-frontend-container
    build:
      context: ./
      dockerfile: ./docker/frontend/dev/Dockerfile
    volumes:
      - ./frontend:/app
    command: "npm run dev"
    environment:
      - HOST=0.0.0.0
      - CALLBACK_REDIRECT='http://localhost:8080/callback'
    ports:
      - "8080:8080"
