# Generated by Django 2.2.5 on 2019-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190906_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='playmusicstats',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
    ]
